const { PGlite } = require(process.env.PGLITE_MODULE_PATH || '@electric-sql/pglite');
const fs = require('node:fs'); const path = require('node:path'); const assert = require('node:assert/strict');
const root = process.env.PRIVACY_REPO || path.resolve(__dirname,'../..');
(async()=>{
 const db=new PGlite();
 const owner='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa', follower='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb', attacker='cccccccc-cccc-4ccc-8ccc-cccccccccccc';
 const trade='11111111-1111-4111-8111-111111111111', second='22222222-2222-4222-8222-222222222222', acc='44444444-4444-4444-8444-444444444444', otherAcc='55555555-5555-4555-8555-555555555555', conn='66666666-6666-4666-8666-666666666666';
 await db.exec(`create role anon; create role authenticated; create role service_role bypassrls; create schema auth; create table auth.users(id uuid primary key);
 create function auth.uid() returns uuid language sql stable as 'select nullif(current_setting(''request.jwt.claim.sub'',true),'''')::uuid';
 grant usage on schema auth to authenticated,anon; grant execute on function auth.uid() to authenticated,anon;
 create table public.trades(id uuid primary key,user_id uuid,account_id uuid,backtest_run_id uuid,data jsonb,instrument text,pnl numeric,direction text,date text,timestamp bigint,signal text,drawings jsonb,is_public boolean,share_notes boolean,created_at timestamptz);
 create table public.connections(id uuid primary key,sender_id uuid,receiver_id uuid,status text,permissions jsonb);
 alter table public.trades enable row level security; alter table public.connections enable row level security;
 create policy trade_owner on public.trades for all to authenticated using(user_id=auth.uid());
 create policy trade_shared on public.trades for select to anon,authenticated using(is_public=true or exists(select 1 from public.connections c where c.status='accepted' and ((c.sender_id=auth.uid() and c.receiver_id=user_id) or(c.receiver_id=auth.uid() and c.sender_id=user_id))));
 create policy conn_read on public.connections for select to authenticated using(sender_id=auth.uid() or receiver_id=auth.uid());
 create policy conn_insert on public.connections for insert to authenticated with check(sender_id=auth.uid());
 create policy conn_receiver on public.connections for update to authenticated using(receiver_id=auth.uid()) with check(receiver_id=auth.uid());
 create policy conn_sender on public.connections for update to authenticated using(sender_id=auth.uid()) with check(sender_id=auth.uid() and status<>'accepted');
 create policy conn_delete on public.connections for delete to authenticated using(sender_id=auth.uid() or receiver_id=auth.uid());
 grant select on public.trades,public.connections to anon; grant select,insert,update,delete on public.trades,public.connections to authenticated;
 create function public.get_dashboard_data() returns jsonb language sql security definer as $$ select jsonb_build_object('trades',coalesce(jsonb_agg(to_jsonb(t)),'[]'::jsonb),'user',jsonb_build_object('id',auth.uid())) from public.trades t where t.user_id=auth.uid() $$;`);
 for(const id of [owner,follower,attacker]) await db.query('insert into auth.users values($1)',[id]);
 const raw={notes:'PRIVATE MAIN',sessionPreNotes:'PRIVATE PRE',sessionPostNotes:'PRIVATE POST',tags:['keep'],data:{notes:'NESTED SECRET'},nested:[{notes:'ARRAY SECRET',keep:true}],noteHistory:{legacy:'OLD HISTORY SECRET'}};
 await db.query('insert into public.trades(id,user_id,account_id,backtest_run_id,data,is_public,share_notes) values($1,$2,$3,$1,$4,true,false),($5,$2,$6,$5,$4,false,false)',[trade,owner,acc,raw,second,otherAcc]);
 const perms={canSeeReviewNotes:true,allowedAccountIds:[acc]};
 await db.query('insert into public.connections values($1,$2,$3,$4,$5)',[conn,follower,owner,'accepted',perms]);
 for(const name of ['20260905173116_backtest_review_atomic_patch.sql','20260905190446_backtest_private_trade_note_history.sql']) await db.exec(fs.readFileSync(path.join(root,'supabase/migrations',name),'utf8'));
 const sql=fs.readFileSync(path.join(root,'supabase/migrations/20260905193801_trade_legacy_notes_privacy_and_owner_consent.sql'),'utf8');
 // Run full migration, roll it back, prove pre-migration bytes/schema unchanged.
 await db.exec(sql.replace(/commit;\s*$/,'rollback;'));
 assert.deepEqual((await db.query('select data from public.trades where id=$1',[trade])).rows[0].data,raw);
 assert.equal((await db.query("select to_regclass('public.trade_private_notes') x")).rows[0].x,null);
 await db.exec(sql);
 const asUser=async uid=>db.exec(`reset role; set role authenticated; set request.jwt.claim.sub='${uid}';`);
 const projection=async(ids,context='owner')=>(await db.query('select public.get_trade_note_projection_v1($1,$2) x',[ids,context])).rows[0].x;
 const pub=async id=>(await db.query('select public.get_public_trade($1) x',[id])).rows[0].x;
 const status=async()=> (await db.query('select public.get_connection_trade_note_consent_v1($1) x',[conn])).rows[0].x;
 const confirm=async(p=perms,accept=false)=>(await db.query('select public.confirm_connection_trade_notes_v1($1,$2,$3) x',[conn,p,accept])).rows[0].x;
 await asUser(owner);
 let p=await projection([trade]);assert.equal(p.rows[0].notes.notes,'PRIVATE MAIN');assert.equal(p.rows[0].notes.noteHistory,undefined);
 let physical=(await db.query('select data from public.trades where id=$1',[trade])).rows[0].data;
 assert(!JSON.stringify(physical).includes('SECRET'));assert(!JSON.stringify(physical).includes('PRIVATE'));assert.deepEqual(physical.tags,['keep']);
 const recovery=(await db.query('select legacy_fragments from public.trade_private_notes where trade_id=$1',[trade])).rows[0].legacy_fragments;
 assert.equal(recovery[0].data.notes,'NESTED SECRET');assert.equal(recovery[0].nested['0'].notes,'ARRAY SECRET');
 assert.equal((await db.query('select public.get_dashboard_data() x')).rows[0].x.trades.find(t=>t.id===trade).data.notes,'PRIVATE MAIN');
 assert.equal((await status()).confirmed,false);
 await db.query('update public.trades set data=data || $2 where id=$1',[trade,{notes:'UPDATED PRIVATE',riskAmount:10}]);
 assert.equal((await projection([trade])).rows[0].notes.notes,'UPDATED PRIVATE');
 await db.query('update public.trades set data=$2 where id=$1',[trade,{tags:['replaced whole blob']}]);
 assert.equal((await projection([trade])).rows[0].notes.notes,'UPDATED PRIVATE');
 const patch=async(updates,expected)=>(await db.query('select public.patch_backtest_trade_review_private_v1($1,$2,$3,$4,null) x',[trade,owner,updates,expected])).rows[0].x;
 assert.equal((await patch({notes:'RPC PRIVATE'},{notes:'UPDATED PRIVATE'})).data.notes,'RPC PRIVATE');
 await assert.rejects(patch({notes:'STALE'},{notes:'UPDATED PRIVATE'}),e=>e.code==='40001');
 assert.equal((await projection([trade])).rows[0].notes.notes,'RPC PRIVATE');
 await db.query('update public.trades set data=data || $2 where id=$1',[trade,{notes:null}]);assert.equal((await projection([trade])).rows[0].notes.notes,null);
 await db.query('update public.trades set data=data || $2 where id=$1',[trade,{notes:'SHARED WHEN APPROVED'}]);
 await asUser(follower);assert.deepEqual((await projection([trade],'connection')).rows,[]);
 await assert.rejects(confirm(),e=>e.code==='42501');
 await assert.rejects(db.query('select * from public.connection_trade_note_consents'),e=>e.code==='42501');
 assert.equal((await db.query('select * from public.trade_private_notes')).rows.length,0);
 await asUser(attacker);
 await assert.rejects(db.query('insert into public.connections values($1,$2,$3,$4,$5)',['77777777-7777-4777-8777-777777777777',attacker,owner,'accepted',perms]),e=>e.code==='42501');
 await db.query('insert into public.connections values($1,$2,$3,$4,$5)',['77777777-7777-4777-8777-777777777777',attacker,owner,'pending',perms]);
 assert.deepEqual((await db.query('select permissions from public.connections where sender_id=$1',[attacker])).rows[0].permissions,{});
 await assert.rejects(db.query("update public.connections set receiver_id=sender_id,sender_id=$2,status='accepted' where id=$1",['77777777-7777-4777-8777-777777777777',owner]),e=>e.code==='42501');
 await asUser(owner);assert.equal((await confirm()).confirmed,true);
 assert.equal((await db.query('select public.get_connection_trade_note_consent_v1($1,$2) x',[conn,{...perms,allowedAccountIds:[otherAcc]}])).rows[0].x.confirmed,false);
 assert.equal((await status()).confirmed,true);
 await asUser(follower);p=await projection([trade,second],'connection');assert.deepEqual(p.rows.map(r=>r.tradeId),[trade]);assert.equal(p.rows[0].notes.notes,'SHARED WHEN APPROVED');
 await asUser(owner);
 await db.query('update public.connections set permissions=$2 where id=$1',[conn,{...perms,allowedAccountIds:[]}]);
 assert.equal((await status()).confirmed,false);
 await assert.rejects(confirm(perms),e=>e.code==='40001');
 await asUser(follower);assert.deepEqual((await projection([trade],'connection')).rows,[]);
 await db.exec('reset role; set role anon; set request.jwt.claim.sub=\'\';');
 assert.equal((await pub(trade)).data.notes,undefined);assert.equal(await pub(second),null);
 assert.equal((await db.query('select data from public.trades where id=$1',[trade])).rows[0].data.notes,undefined);
 await assert.rejects(db.query('select * from public.trade_private_notes'),e=>e.code==='42501');
 await asUser(owner);await db.query('update public.trades set share_notes=true where id=$1',[trade]);
 await db.exec('reset role; set role anon; set request.jwt.claim.sub=\'\';');
 p=await pub(trade);assert.equal(p.data.notes,'SHARED WHEN APPROVED');assert.equal(p.data.noteHistory,undefined);assert.equal(p.data.data?.notes,undefined);
 await asUser(owner);await db.query('update public.trades set share_notes=false where id=$1',[trade]);
 await db.exec('reset role; set role anon; set request.jwt.claim.sub=\'\';');assert.equal((await pub(trade)).data.notes,undefined);
 await asUser(attacker);
 await assert.rejects(db.query('update public.connections set permissions=$2 where id=$1',['77777777-7777-4777-8777-777777777777',perms]),e=>e.code==='42501');
 await assert.rejects(db.query('insert into public.connection_trade_note_consents(connection_id,receiver_id,sender_id,scope) values($1,$2,$3,$4)',['77777777-7777-4777-8777-777777777777',owner,attacker,{}]),e=>e.code==='42501');
 await asUser(owner);
 const accepted=(await db.query('select public.confirm_connection_trade_notes_v1($1,$2,true) x',['77777777-7777-4777-8777-777777777777',perms])).rows[0].x;
 assert.equal(accepted.confirmed,true);
 await asUser(attacker);assert.equal((await projection([trade],'connection')).rows.length,1);
 await asUser(follower);
 const followerTrade='88888888-8888-4888-8888-888888888888';
 await db.query('insert into public.trades(id,user_id,account_id,data,is_public) values($1,$2,$3,$4,false)',[followerTrade,follower,acc,{notes:'FOLLOWER PRIVATE'}]);
 assert.equal((await projection([followerTrade])).rows[0].notes.notes,'FOLLOWER PRIVATE');
 await asUser(owner);assert.deepEqual((await projection([followerTrade],'connection')).rows,[]);
 await assert.rejects(db.query('update public.trade_private_notes set notes=$2 where trade_id=$1',[trade,{notes:'bypass'}]),e=>e.code==='42501');
 await assert.rejects(projection([trade],'invalid'),e=>e.code==='22023');
 console.log(JSON.stringify({engine:'PGlite PostgreSQL WASM',transactionRollback:true,privateBackfill:true,nestedRecoveryPreserved:true,legacyWritesSplit:true,missingKeyPreserves:true,explicitNullClears:true,ownerDashboardCompatibility:true,privateCAS:true,legacyConnectionsRequireReconfirmation:true,forgedAcceptanceRejected:true,identityRewriteRejected:true,receiverConfirmation:true,accountScopeEnforced:true,permissionChangesRevokeConsent:true,publicShareOnOffPreserved:true,directTableAndAnonPrivateAccessDenied:true,atomicReceiverAccept:true,senderPermissionMutationDenied:true,serverOwnedMarker:true,reverseDirectionDenied:true,directPrivateWriteDenied:true,staleDisplayedScopeNotConfirmed:true,checks:22},null,2));
 await db.close();
})().catch(e=>{console.error(e);process.exitCode=1});
