// Local-only SQL verification. Supply PGLITE_MODULE_PATH if PGlite lives in a temporary runtime.
const { PGlite } = require(process.env.PGLITE_MODULE_PATH || '@electric-sql/pglite');
const { readFileSync } = require('node:fs');
const assert = require('node:assert/strict');
(async () => {
 const db = new PGlite();
 const owner='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa', other='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb', id='11111111-1111-4111-8111-111111111111';
 await db.exec(`create role anon; create role authenticated; create schema auth;
 create function auth.uid() returns uuid language sql stable as 'select nullif(current_setting(''request.jwt.claim.sub'',true),'''')::uuid';
 grant usage on schema auth to authenticated; grant execute on function auth.uid() to authenticated;
 create table public.trades(id uuid primary key,user_id uuid,account_id uuid,backtest_run_id uuid,data jsonb,instrument text,pnl numeric,direction text,date text,timestamp bigint,signal text,drawings jsonb,is_public boolean);
 alter table public.trades enable row level security;
 create policy own on public.trades to authenticated using (user_id=auth.uid()) with check(user_id=auth.uid());
 grant select,update on public.trades to authenticated;`);
 await db.exec(readFileSync(require('node:path').resolve(__dirname, '../../supabase/migrations/20260905173116_backtest_review_atomic_patch.sql'),'utf8'));
 await db.query('insert into public.trades(id,user_id,account_id,backtest_run_id,data,pnl) values($1,$2,$2,$1,$3,0)',[id,owner,{notes:'old',tags:['old'],screenshot:'https://example.invalid/old',screenshots:['https://example.invalid/old','https://example.invalid/second']}]);
 await db.exec(`set role authenticated; set request.jwt.claim.sub='${owner}';`);
 const patch=async(updates={},expected={},url=null,ownerId=owner)=> (await db.query('select public.patch_backtest_trade_review($1,$2,$3,$4,$5) result',[id,ownerId,updates,expected,url])).rows[0].result.data;
 const initial=await patch();
 assert.equal(initial.id,id);assert.equal(initial.accountId,owner);assert.equal(initial.backtestRunId,id);assert.equal(initial.pnl,0);
 await patch({notes:'new note'},{notes:initial.notes});
 let result=await patch({tags:['new tag']},{tags:initial.tags});
 assert.equal(result.notes,'new note');assert.deepEqual(result.tags,['new tag']);
 await assert.rejects(patch({notes:'stale editor'},{notes:'old'}),err=>err.code==='40001');
 result=await patch({notes:'new note'},{notes:'old'});assert.equal(result.notes,'new note');
 await patch({}, {}, 'https://example.invalid/third');
 result=await patch({}, {}, 'https://example.invalid/fourth');
 assert.equal(result.screenshots.length,4); assert.equal(result.screenshot,'https://example.invalid/old');assert.equal(result.notes,'new note');
 result=await patch({}, {}, 'https://example.invalid/fourth');assert.equal(result.screenshots.length,4);
 await assert.rejects(patch({notes:'intruder'},{notes:'new note'},null,other),err=>err.code==='42501');
 await db.exec(`set request.jwt.claim.sub='${other}';`);
 await assert.rejects(patch({}, {}, null,other),err=>err.code==='P0002');
 await db.exec(`set request.jwt.claim.sub='${owner}';`);
 result=await patch({pnl:15},{pnl:0}); assert.equal(result.pnl,15);
 assert.equal((await db.query('select pnl from public.trades')).rows[0].pnl,'15');
 const grants=(await db.query("select has_function_privilege('anon','public.patch_backtest_trade_review(text,uuid,jsonb,jsonb,text)','execute') anon, has_function_privilege('authenticated','public.patch_backtest_trade_review(text,uuid,jsonb,jsonb,text)','execute') authenticated")).rows[0];
 assert.equal(grants.anon,false);assert.equal(grants.authenticated,true);
 console.log(JSON.stringify({database:'PGlite (real PostgreSQL WASM)',disjointEditsPreserved:true,staleEditedFieldRejected:true,idempotentRetry:true,concurrentGalleryAppendPreserved:true,ownerMismatchRejected:true,rlsOtherOwnerDenied:true,rootColumnsSynchronized:true,anonExecuteDenied:true,canonicalSnapshotIdentityAndFacts:true,checks:10},null,2));
 await db.close();
})().catch(e=>{console.error(e);process.exitCode=1});
