// Local-only verification, uses PostgreSQL WASM and fabricated users/trades.
const { PGlite } = require(process.env.PGLITE_MODULE_PATH || '@electric-sql/pglite');
const { readFileSync } = require('node:fs');
const assert = require('node:assert/strict');
const path = require('node:path');
(async () => {
 const db = new PGlite();
 const owner='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa', other='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb', id='11111111-1111-4111-8111-111111111111';
 const root=process.env.PRIVATE_NOTES_REPO || path.resolve(__dirname, '../..');
 await db.exec(`create role anon; create role authenticated; create schema auth;
 create table auth.users(id uuid primary key);
 create function auth.uid() returns uuid language sql stable as 'select nullif(current_setting(''request.jwt.claim.sub'',true),'''')::uuid';
 grant usage on schema auth to authenticated; grant execute on function auth.uid() to authenticated;
 create table public.trades(id uuid primary key,user_id uuid,account_id uuid,backtest_run_id uuid,data jsonb,instrument text,pnl numeric,direction text,date text,timestamp bigint,signal text,drawings jsonb,is_public boolean);
 alter table public.trades enable row level security;
 create policy own on public.trades to authenticated using (user_id=auth.uid()) with check(user_id=auth.uid());
 create policy shared on public.trades for select to anon,authenticated using (is_public=true);
 grant select on public.trades to anon; grant select,update on public.trades to authenticated;`);
 await db.exec(readFileSync(path.join(root,'supabase/migrations/20260905173116_backtest_review_atomic_patch.sql'),'utf8'));
 await db.exec(readFileSync(path.join(root,'supabase/migrations/20260905190446_backtest_private_trade_note_history.sql'),'utf8'));
 await db.query('insert into auth.users values($1),($2)',[owner,other]);
 await db.query('insert into public.trades(id,user_id,account_id,backtest_run_id,data,pnl,is_public) values($1,$2,$2,$1,$3,0,true)',[id,owner,{notes:'legacy shared note',tags:['old']}]);
 await db.exec(`set role authenticated; set request.jwt.claim.sub='${owner}';`);
 const patch=async(updates={},expected={},url=null,ownerId=owner,fn='patch_backtest_trade_review_private_v1')=> (await db.query(`select public.${fn}($1,$2,$3,$4,$5) result`,[id,ownerId,updates,expected,url])).rows[0].result;
 const revision=(n,text,phase='before')=>({id:`op${n}:${phase}`,noteId:`note-op1-${phase}`,operationId:`op${n}`,revision:n,parentRevision:n-1,supersedesId:n===1?null:`op${n-1}:${phase}`,phase,operation:'write',text,clientCapturedAt:1000+n,captureContext:{marketTime:60,maxRevealedMarketTime:60,entryMarketTime:120,exitMarketTime:180,closedTradeReview:false},marketTime:60,knowledgeHorizonTime:60,retrospective:false,retrospectiveReason:null,source:'user'});
 const h1={version:1,revision:1,revisions:[revision(1,'private plan')]};
 const h2={version:1,revision:2,revisions:[...h1.revisions,revision(2,'private update')]};
 const initial=await patch();assert.deepEqual(initial.privateNotes,{version:1,storage:'owner-table'});assert.equal(initial.data.noteHistory,undefined);
 let result=await patch({noteHistory:h1,notes:'new legacy'},{notes:'legacy shared note'});
 assert.deepEqual(result.data.noteHistory,h1);
 assert.equal((await db.query('select data from public.trades')).rows[0].data.noteHistory,undefined);
 assert.deepEqual((await db.query('select history from public.backtest_trade_note_histories')).rows[0].history,h1);
 await patch({noteHistory:h2},{noteHistory:h1});
 result=await patch({noteHistory:h1},{});assert.deepEqual(result.data.noteHistory,h2);
 result=await patch({tags:['new']},{tags:['old']});assert.deepEqual(result.data.noteHistory,h2);
 await assert.rejects(patch({noteHistory:{...h2,revisions:[revision(1,'stale edit'),h2.revisions[1]]}},{noteHistory:h1}),err=>err.code==='40001');
 await assert.rejects(patch({noteHistory:{version:1,revision:0,revisions:[]}},{noteHistory:h2}),err=>err.code==='22023');
 const h3={version:1,revision:3,revisions:[...h2.revisions,revision(3,'rollback')]};
 await assert.rejects(patch({noteHistory:h3},{noteHistory:h2},'bad-url'),err=>err.code==='22023');
 assert.deepEqual((await patch()).data.noteHistory,h2);
 result=await patch({noteHistory:h3},{noteHistory:h2},null,owner,'patch_backtest_trade_review');assert.deepEqual(result.data.noteHistory,h3);
 assert.equal((await db.query('select data from public.trades')).rows[0].data.noteHistory,undefined);
 await assert.rejects(patch({}, {}, null,other),err=>err.code==='42501');
 await db.exec(`set request.jwt.claim.sub='${other}';`);
 assert.equal((await db.query('select * from public.backtest_trade_note_histories')).rows.length,0);
 assert.equal((await db.query('select data from public.trades')).rows[0].data.noteHistory,undefined);
 await assert.rejects(patch({}, {}, null,other),err=>err.code==='P0002');
 await assert.rejects(db.query('insert into public.backtest_trade_note_histories(trade_id,user_id,history) values($1,$2,$3)',[id,other,h1]),err=>err.code==='42501');
 await db.exec('reset role; set role anon;');
 assert.equal((await db.query('select data from public.trades')).rows[0].data.noteHistory,undefined);
 await assert.rejects(db.query('select * from public.backtest_trade_note_histories'),err=>err.code==='42501');
 await assert.rejects(patch(),err=>err.code==='42501');
 console.log(JSON.stringify({database:'PGlite real PostgreSQL WASM',privateTableOnly:true,ownerReadAndAppend:true,sharedTradeDoesNotContainHistory:true,otherOwnerDenied:true,anonymousDenied:true,casConflictPreservesLedger:true,prefixRetryPreservesNewerSuffix:true,appendOnly:true,atomicRollbackAfterPrivateWrite:true,legacyRpcSafelySplitsHistory:true,capabilitySnapshot:true,checks:11},null,2));
 await db.close();
})().catch(e=>{console.error(e);process.exitCode=1});
