-- Push notifications: per-device subscriptions + delivery log.
--
-- PROČ: dosud žila push subscription jako jediný objekt v `profiles.preferences`
-- (JSON blob). To mělo dvě chyby:
--   1. jeden uživatel = jedna subscription → druhé zařízení přepsalo první,
--      alerty pak chodily náhodně jen na jedno z nich,
--   2. blob se ukládá last-write-wins (viz App.tsx komentář u applyPreferences),
--      takže cron při čištění expirovaného odběru přepisoval i uživatelova
--      nastavení starým snapshotem.
-- Subscription proto dostává vlastní tabulku, jeden řádek = jedno zařízení.
--
-- `alert_deliveries` je zároveň idempotence i log doručení: cron běží každou
-- minutu a okna alertů jsou ±1 min, takže bez tohohle záznamu se stejný alert
-- odešle až 3× (sociální dokonce 5×, ty mají 5min lookback).

begin;

create table public.push_subscriptions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  endpoint text not null,
  p256dh text not null,
  auth text not null,
  -- Diagnostika: ať jde v Settings poznat, které zařízení je které.
  user_agent text,
  is_standalone boolean,
  platform text,
  created_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  -- Naplní se, až push service vrátí 404/410. Řádek nemažeme hned, ať je
  -- v Settings vidět "tohle zařízení vypadlo" místo tichého zmizení.
  expired_at timestamptz,
  last_error text,
  -- Endpoint je globálně unikátní identifikátor odběru. Unique bez user_id:
  -- když se u zařízení přihlásí jiný účet, odběr má patřit jemu, ne oběma.
  unique (endpoint)
);

create index push_subscriptions_user_active_idx
  on public.push_subscriptions (user_id)
  where expired_at is null;

create table public.alert_deliveries (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  -- Typ alertu ve tvaru, jaký používá send-alerts.ts (např. 'guardian-t15',
  -- 'session-start-<id>', 'social-trade-<uuid>').
  alert_type text not null,
  -- Obchodní den v Europe/Prague, ke kterému alert patří. Spolu s alert_type
  -- tvoří klíč idempotence: jeden alert daného typu jednou za den.
  alert_date date not null,
  subscription_id uuid references public.push_subscriptions(id) on delete set null,
  status text not null check (status in ('sent', 'expired', 'failed')),
  status_code int,
  error text,
  title text,
  body text,
  created_at timestamptz not null default now(),
  -- Idempotence je na (user, typ, den, zařízení): každé zařízení dostane alert
  -- právě jednou. Cron se o vložení pokusí PŘED odesláním, konflikt = přeskoč.
  unique (user_id, alert_type, alert_date, subscription_id)
);

create index alert_deliveries_user_created_idx
  on public.alert_deliveries (user_id, created_at desc);

alter table public.push_subscriptions enable row level security;
alter table public.alert_deliveries enable row level security;

-- Klient si spravuje vlastní odběry (zapnutí/vypnutí notifikací, refresh po
-- rotaci endpointu). Zápis do alert_deliveries dělá výhradně cron přes service
-- role, uživatel má jen čtení pro diagnostiku v Settings.
create policy push_subscriptions_owner_select
  on public.push_subscriptions for select to authenticated
  using ((select auth.uid()) = user_id);
create policy push_subscriptions_owner_insert
  on public.push_subscriptions for insert to authenticated
  with check ((select auth.uid()) = user_id);
create policy push_subscriptions_owner_update
  on public.push_subscriptions for update to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);
create policy push_subscriptions_owner_delete
  on public.push_subscriptions for delete to authenticated
  using ((select auth.uid()) = user_id);

create policy alert_deliveries_owner_select
  on public.alert_deliveries for select to authenticated
  using ((select auth.uid()) = user_id);

revoke all on public.push_subscriptions from anon, authenticated;
revoke all on public.alert_deliveries from anon, authenticated;
grant select, insert, update, delete on public.push_subscriptions to authenticated;
grant select on public.alert_deliveries to authenticated;

commit;
