-- Isolated raw/live Tradecopia shadow store.
-- Nothing in the application reads these tables yet. They exist solely for
-- lossless capture and reliability verification before any cut-over.

begin;

create table public.tradecopia_shadow_sync_runs (
  id uuid primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  source text not null default 'tradecopia',
  agent_version text not null,
  status text not null default 'processing'
    check (status in ('processing', 'completed', 'failed')),
  captured_at timestamptz not null,
  completed_at timestamptz,
  main_db_mtime_ms bigint,
  logs_db_mtime_ms bigint,
  schema_hash text not null,
  schemas jsonb not null default '{}'::jsonb,
  row_counts jsonb not null default '{}'::jsonb,
  changed_counts jsonb not null default '{}'::jsonb,
  warning text,
  error text,
  created_at timestamptz not null default now()
);

create table public.tradecopia_shadow_current (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  source text not null default 'tradecopia',
  source_db text not null check (source_db in ('main', 'logs')),
  source_table text not null,
  source_key text not null,
  account_ext_id bigint,
  source_updated_at timestamptz,
  payload_hash text not null,
  payload jsonb not null,
  is_present boolean not null default true,
  first_seen_at timestamptz not null,
  last_seen_at timestamptz not null,
  last_changed_at timestamptz not null,
  sync_run_id uuid references public.tradecopia_shadow_sync_runs(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, source, source_db, source_table, source_key)
);

create table public.tradecopia_shadow_changes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  source text not null default 'tradecopia',
  source_db text not null check (source_db in ('main', 'logs')),
  source_table text not null,
  source_key text not null,
  account_ext_id bigint,
  change_type text not null check (change_type in ('inserted', 'updated', 'deleted')),
  observed_at timestamptz not null,
  source_updated_at timestamptz,
  payload_hash text not null,
  payload jsonb not null,
  sync_run_id uuid not null references public.tradecopia_shadow_sync_runs(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (sync_run_id, source_db, source_table, source_key)
);

create index tradecopia_shadow_runs_user_captured_idx
  on public.tradecopia_shadow_sync_runs (user_id, captured_at desc);
create index tradecopia_shadow_current_user_table_idx
  on public.tradecopia_shadow_current (user_id, source_db, source_table, is_present, last_seen_at desc);
create index tradecopia_shadow_current_account_idx
  on public.tradecopia_shadow_current (user_id, account_ext_id, last_seen_at desc)
  where account_ext_id is not null;
create index tradecopia_shadow_current_run_idx
  on public.tradecopia_shadow_current (sync_run_id)
  where sync_run_id is not null;
create index tradecopia_shadow_changes_user_table_idx
  on public.tradecopia_shadow_changes (user_id, source_db, source_table, observed_at desc);
create index tradecopia_shadow_changes_account_idx
  on public.tradecopia_shadow_changes (user_id, account_ext_id, observed_at desc)
  where account_ext_id is not null;
create index tradecopia_shadow_changes_run_idx
  on public.tradecopia_shadow_changes (sync_run_id);

alter table public.tradecopia_shadow_sync_runs enable row level security;
alter table public.tradecopia_shadow_current enable row level security;
alter table public.tradecopia_shadow_changes enable row level security;

create policy tradecopia_shadow_runs_owner_select
  on public.tradecopia_shadow_sync_runs for select to authenticated
  using ((select auth.uid()) = user_id);
create policy tradecopia_shadow_current_owner_select
  on public.tradecopia_shadow_current for select to authenticated
  using ((select auth.uid()) = user_id);
create policy tradecopia_shadow_changes_owner_select
  on public.tradecopia_shadow_changes for select to authenticated
  using ((select auth.uid()) = user_id);

revoke all on public.tradecopia_shadow_sync_runs from anon, authenticated;
revoke all on public.tradecopia_shadow_current from anon, authenticated;
revoke all on public.tradecopia_shadow_changes from anon, authenticated;
grant select on public.tradecopia_shadow_sync_runs to authenticated;
grant select on public.tradecopia_shadow_current to authenticated;
grant select on public.tradecopia_shadow_changes to authenticated;

create view public.tradecopia_shadow_latest
with (security_invoker = true)
as
select
  user_id, source, source_db, source_table, source_key, account_ext_id,
  source_updated_at, payload_hash, payload, first_seen_at, last_seen_at,
  last_changed_at, sync_run_id
from public.tradecopia_shadow_current
where is_present;

revoke all on public.tradecopia_shadow_latest from public, anon;
grant select on public.tradecopia_shadow_latest to authenticated;

commit;
